//
// Created by 19693 on 2023/6/23.
//

#ifndef XMB_WIRELESSDEBUGER_COMPONENTS_XMB_FUNCTIONMODULES_WIFI_WIFI_INFO_H_
#define XMB_WIRELESSDEBUGER_COMPONENTS_XMB_FUNCTIONMODULES_WIFI_WIFI_INFO_H_
//#include "Configure.h"
#define EXAMPLE_ESP_WIFI_SSID "xtxWork"
#define EXAMPLE_ESP_WIFI_PASS "WorkWithXTX"
#define EXAMPLE_ESP_MAXIMUM_RETRY 5


#endif //XMB_WIRELESSDEBUGER_COMPONENTS_XMB_FUNCTIONMODULES_WIFI_WIFI_INFO_H_
